version:  "3"
services:
  aoc-db:
    image: postgres:14
    container_name: aoc-db
    restart: always
    ports:
    - "127.0.0.1:54320:5432"
    expose:
    - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: aoc
      POSTGRES_USER: postgres
